version: "3.3"

services:
  db:
    image: postgres@sha256:4ec37d2a07a0067f176fdcc9d4bb633a5724d2cc4f892c7a2046d054bb6939e5
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    image: pygoat/pygoat
    command: gunicorn --bind 0.0.0.0:8000 --workers 6 pygoat.wsgi
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - migration
      - db
  migration:
    image: pygoat/pygoat@sha256:26a75f7cd023a9c77158f55c54dbb405ab2b77aaf46dfb888f209735fa0d0b54
    command: python pygoat/manage.py migrate --noinput
    volumes:
      - .:/app
    depends_on:
      - db
